#---------------------------------------------------------------------------
# Dockefile to build Docker Image of application container for spring_DB running on mysql image
#---------------------------------------------------------------------------

FROM mysql:latest
# Setting vars 
ENV MYSQL_ALLOW_EMPTY_PASSWORD true
ENV MYSQL_USER petclinic 
ENV MYSQL_DATABASE petclinic

# Set on run via -e  
# MYSQL_PASSWORD
# MYSQL_ROOT_PASSWORD

# EXPOSE 3306

