#---------------------------------------------------------------------------
# Dockefile to build Docker Image of application container for spring_DB running on mysql image
#---------------------------------------------------------------------------

FROM mysql:latest
# Setting vars  
ENV MYSQL_USER $DB_USER
ENV MYSQL_DATABASE $DB_NAME

# Set on run via -e  
# MYSQL_PASSWORD
# MYSQL_ROOT_PASSWORD

# EXPOSE 3306

