services:

  app:
    image: localhost:5000/my-petclinic-app
    ports:
      -  8080:8080
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: $manager_IP:5001/my-petclinic-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - /home/vagrant/docker/conf.d:/etc/mysql/conf.d:ro
      - /home/vagrant/docker/mysql:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == worker]