# base build image
FROM mysql:latest

# setting environment variables for database name, user and password for it  
ENV MYSQL_DATABASE ${DB_NAME}
ENV MYSQL_USER ${DB_USER}
ENV MYSQL_PASSWORD ${DB_PASS}