CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;

ALTER DATABASE $MYSQL_DATABASE
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON $MYSQL_USER.* TO '$MYSQL_USER' IDENTIFIED BY '$MYSQL_PASS';

